package main

import (
	_ "github.com/ZmaximillianZ/stskp_sport_api/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/ZmaximillianZ/stskp_sport_api/internal/controllers"
	"github.com/ZmaximillianZ/stskp_sport_api/internal/logging"
	"github.com/ZmaximillianZ/stskp_sport_api/internal/repository"
	"github.com/ZmaximillianZ/stskp_sport_api/internal/routers"
	"github.com/ZmaximillianZ/stskp_sport_api/internal/setting"
	"github.com/jmoiron/sqlx"

	"github.com/joho/godotenv"

	"log"
)

const maxIdleConns = 100
const maxOpenConns = 10

var conf *setting.Setting

// init is invoked before main()
// @title Swagger Example API
// @version 1.0
// @description This is a sample server Petstore server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html
// @securityDefinitions.apikey JWT
// @in header
// @name X-AUTH-TOKEN
// @host localhost:8081
func main() {
	if err := godotenv.Load(); err != nil {
		log.Print("No .env file found")
	}

	conf = setting.LoadSetting()
	logging.Setup()
	repository.Setup()
	routersInit := routers.InitRouter()

	db, err := sqlx.Connect("pgx", conf.DBConfig.URL) // TODO: move all configuration to database package
	if err != nil {
		log.Fatalf("postgres.Setup err: %v\n", err)
	}

	db.SetMaxIdleConns(maxIdleConns)
	db.SetMaxOpenConns(maxOpenConns)

	userRepo := repository.NewUserRepository(db)
	userController := controllers.NewUserController(userRepo)
	demoGroup := routersInit.Group("/api/demo")
	demoGroup.GET("users/:id", userController.GetUserByID)

	if err := routersInit.Run(":" + conf.ServerConfig.Port); err != nil {
		logging.Error(err)
	}
}
