POST http://localhost:8081/api/user/auth?username=qwe&password=123123
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###

POST http://localhost:8081/api/user/create?username=dimm&password=123123
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

####

PATCH http://localhost:8081/api/v1/users/12/update
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImE3ZjJlOTg4MzVjMWZiNjdlOWFhOWYxZmJhYWU1ZTk4IiwicGFzc3dvcmQiOiI4MjdjY2IwZWVhOGE3MDZjNGMzNGExNjg5MWY4NGU3YiIsImV4cCI6MTYxMjUxODcyNywiaXNzIjoic3Rza3AtYXBpIn0.RKw6YlNbiZjaaZ9LL-591bqJR6FMFDOi8wCWWGiCD3E

{
  "email": "mail@ama.com",
  "state": 5,
  "username": "dimm"
}
###

GET http://localhost:8081/api/v1/users?Criteria%5B0%5D%5Bfield%5D=state&Criteria%5B0%5D%5BValue%5D=1&Criteria%5B0%5D%5BCondition%5D=%3E&order%5Bid%5D=DESC
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImE3ZjJlOTg4MzVjMWZiNjdlOWFhOWYxZmJhYWU1ZTk4IiwicGFzc3dvcmQiOiI4MjdjY2IwZWVhOGE3MDZjNGMzNGExNjg5MWY4NGU3YiIsImV4cCI6MTYxMjUxODcyNywiaXNzIjoic3Rza3AtYXBpIn0.RKw6YlNbiZjaaZ9LL-591bqJR6FMFDOi8wCWWGiCD3E

//{
//  "criteria": {
//   "state": [">", "1"],
//   "field": [">", "1"]
//  },
//  "limit": 0,
//  "offset": 0,
//  "order": {"id": "DESC"}
//}

###"id": [">", "4"],
###"state": [">=", "1"]