POST https://localhost:1323/api/v1/auth?username=john&password=123123
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###

###

POST https://localhost:1323/api/v1/create?username=some_test_6&password=123123
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

####

PUT https://localhost:1323/api/v1/users/4
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJc3N1ZXIiOiJzdHNrcC1hcGkiLCJhZG1pbiI6dHJ1ZSwiZXhwIjoxNjI3MDI3OTI5LCJuYW1lIjoiam9obiJ9.yW_fTlSEg0GgJhn2mav9InpgLu1aFe92wQOBIgbnPbo

{
  "email": "test0624@mail.com",
  "state": 6,
  "username": "new edit"
}

###

GET https://localhost:1323/api/v1/users/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJc3N1ZXIiOiJzdHNrcC1hcGkiLCJhZG1pbiI6dHJ1ZSwiZXhwIjoxNjI3MDI3OTI5LCJuYW1lIjoiam9obiJ9.yW_fTlSEg0GgJhn2mav9InpgLu1aFe92wQOBIgbnPbo

###

GET https://localhost:1323/api/v1/users/
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJc3N1ZXIiOiJzdHNrcC1hcGkiLCJhZG1pbiI6dHJ1ZSwiZXhwIjoxNjI2ODgxODk0LCJuYW1lIjoiam9obiJ9.CG3e8NAiSgVNs1jgnQXJROSztbS3M_hKMexvfQHLQaA

###

DELETE https://localhost:1323/api/v1/users/4
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJc3N1ZXIiOiJzdHNrcC1hcGkiLCJhZG1pbiI6dHJ1ZSwiZXhwIjoxNjI2ODgxODk0LCJuYW1lIjoiam9obiJ9.CG3e8NAiSgVNs1jgnQXJROSztbS3M_hKMexvfQHLQaA

############# WORKOUT #############

POST https://localhost:1323/api/v1/workout/create
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "description": "My first workout",
  "user_id": 2
}

####

GET https://localhost:1323/api/v1/workout/all
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJc3N1ZXIiOiJzdHNrcC1hcGkiLCJhZG1pbiI6dHJ1ZSwiZXhwIjoxNjI3MDI3OTI5LCJuYW1lIjoiam9obiJ9.yW_fTlSEg0GgJhn2mav9InpgLu1aFe92wQOBIgbnPbo

###