CREATE TABLE users (
    id              int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        varchar(50) NOT NULL,
    password_hash   int NOT NULL,
    state           int2 CONSTRAINT state_check CHECK (state > 0 and state <=5),
    created_at      timestamp,
    email           varchar(255) NOT NULL
);
